services:
  frontend-admin:
    container_name: talent-showcase-frontend-admin

    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://api.starion.app/api/v1

    restart: unless-stopped

    env_file:
      - .env.production

    ports:
      - "3001:3001"
